name: "Actions Workflow"
on: [push,pull_request]
jobs:
    RunningShellScripts:
        runs-on: ubuntu-latest
        steps:
            - name: "Echo a String"
              run: echo "Hello World"
            - name: "Multiline Script"
              run: |
                node -v
                npm -v

    ImplementationOfActions:
        runs-on: ubuntu-latest
        steps:
            - name: "Display  ubuntu version"
              run: cat /etc/os-release
            - name: "Display release verison of runner"
              run: |
                uname -a
                ls -la /home

              
            
        
